version: '3'
services:
  db:
    build: ./postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./backup:/pg_backups
    ports:
      - "5432:5432"
  web:
    build: ./flask
    command: python app.py
    volumes:
      - ./www:/www
    ports:
      - "5050:5050"
    depends_on:
      - db
